name: Action that sends the SIAN code to webapp's repo
on: [push]
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: "Download latest gh-cli"
        env: 
          VERSION: `curl  "https://api.github.com/repos/cli/cli/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c2-` 
        run: |
          wget https://github.com/cli/cli/releases/download/v${VERSION}/gh_${VERSION}_linux_amd64.tar.gz
      - name: "Install gh-cli" 
        run: |
          tar xvf gh_${VERSION}_linux_amd64.tar.gz
          # cp gh_${VERSION}_linux_amd64/bin/gh /usr/local/bin/
          # gh version
      - name: "print git status"
        run: |
          git status -s
        # chmod +x "${GITHUB_WORKSPACE}/.github/script.sh"

        # ${GITHUB_WORKSPACE}/.github/script.sh


